{
 "title": "Harbor image vulnerabilities",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(harbor_project_repo_total,project_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Vulnerabilities in projects",
   "type": "gauge",
   "description": "Total number of vulnerabilities in images per project",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (project) (harbor_image_vulnerabilities)",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Proxy projects vulnerabilities",
   "type": "graph",
   "description": "Number of vulnerabilities in images pulled down via proxy projects",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (project,repository) (harbor_image_vulnerabilities{project=~\"proxy.*\"})",
     "legendFormat": "{{project}}/{{repository}}"
    }
   ]
  },
  {
   "title": "All vulnerabilities in $project project by severity",
   "type": "stat",
   "description": "Total number of vulnerabilities in $project project divided by severity",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "repeat": "project",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (project,severity) (harbor_image_vulnerabilities{project=\"$project\",severity=\"Critical\"})",
     "legendFormat": "{{severity}}"
    },
    {
     "expr": "sum by (project,severity) (harbor_image_vulnerabilities{project=\"$project\",severity=\"High\"})",
     "legendFormat": "{{severity}}"
    },
    {
     "expr": "sum by (project,severity) (harbor_image_vulnerabilities{project=\"$project\",severity=\"Medium\"})",
     "legendFormat": "{{severity}}"
    },
    {
     "expr": "sum by (project,severity) (harbor_image_vulnerabilities{project=\"$project\",severity=\"Low\"})",
     "legendFormat": "{{severity}}"
    },
    {
     "expr": "sum by (project,severity) (harbor_image_vulnerabilities{project=\"$project\",severity=\"Unknown\"})",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "$project repositories vulnerabilities",
   "type": "graph",
   "description": "Number of vulnerabilities in the latest pushed image into each repository in the project",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "repeat": "project",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (project,repository) (harbor_image_vulnerabilities{project=\"$project\"})",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Critical vulnerabilities details",
   "type": "table",
   "description": "Detailed information about found vulnerabilities with critical and high severity levels",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (project, repository, description, package, id, version, fix_version, severity) (harbor_image_vulnerabilities{project=~\"$project\",severity=~\"Critical|High\"})"
    }
   ]
  }
 ]
}