{{- if .Values.serviceMonitor.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "harbor-vulnerabilities-exporter.name" . }}
  labels:
{{- include "harbor-vulnerabilities-exporter.labels" . | nindent 4 }}
spec:
  jobLabel: harbor-vulnerabilities-exporter
  selector:
    matchLabels:
{{- include "harbor-vulnerabilities-exporter.labels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      interval: {{ .Values.serviceMonitor.scrapeInterval }}
      honorLabels: true
{{- end }}
