---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor-vulnerabilities-exporter.name" . }}
  labels:
{{- include "harbor-vulnerabilities-exporter.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.exporterPort }}
      targetPort: {{ .Values.exporterPort }}
      protocol: TCP
      name: metrics
  selector:
{{- include "harbor-vulnerabilities-exporter.labels" . | nindent 4 }}
