name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  unit:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: make test

      - name: Run linter
        run: make lint
